spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/syndicate_loans
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false

blockchain:
  service:
    host: http://localhost:9393
    connectionTimeout: PT5S
    readTimeout: PT2M

payments-calculator:
  service:
    host: http://localhost:9999/api/v1/
    connectionTimeout: PT5S
    readTimeout: PT2M


jwt:
  key: secretKey
  expiration-time: 5000000

server:
  port: 8080