spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/syndicate_loans
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

blockchain:
  service:
    host:
      http://localhost:9393

jwt:
  key: secretKey
  expiration-time: 5000000

server:
  port: 8080